### ISSUE TITLE
Restore GitHub Links post-CRAN GH_TOKEN addition

### ISSUE THREAD

**Issue by coatless** [coatless-rpkg/rcppensmallen#26]
In PR #25's https://github.com/coatless/rcppensmallen/pull/25/commits/29ed79badb75926d3e0bb535d672a95dc63f5577 , we lost the ability to fully link to the Ensmallen commits on GitHub due to the `NEWS.md`  file having too many links to pages on GitHub. e.g.

```
From: NEWS.md
Status: 429
Message: Too Many Requests
```

From Slack, @eddelbuettel mentioned that Kurt Hornik is working to add a `GITHUB_PAT`/`GITHUB_TOKEN` to allow for increased traffic rates to GitHub. Once this goes through, we can restore by running: 

```r
# Read in news items
items = readLines("NEWS.md")

# Convert
items = sub(
          "mlpack/ensmallen#([0-9]+)",
          "[#\1](https://github.com/mlpack/ensmallen/pulls/\1)", 
          items
         )

# Write out fixed items
writeLines(items, "NEWS.md")
```

**Comment by eddelbuettel** [comment]
Just noticed old post:  AFAICT both Dortmund and Vienna _eventually_ did that as I no longer get nags, and I never removed the (numerous) links in either Rcpp or RcppArmadillo -- so I'd say restore ahead.
