### ISSUE TITLE
Error on installation in R 4.1.3(macport version) under macos Monterey 

### ISSUE THREAD

**Issue by gpasa** [coatless-rpkg/rcppensmallen#48]
Hi, while installing the package I got the following error messages

    installing source package ‘RcppEnsmallen’ ...
    ** package ‘RcppEnsmallen’ successfully unpacked and MD5 sums checked
    ** using staged installation
    ** libs
    /opt/local/bin/clang++-mp-13 -std=gnu++11 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I'/Users/gpasa/Library/R/x86_64/4.1/library/Rcpp/include' -I'/Users/gpasa/Library/R/x86_64/4.1/library/RcppArmadillo/include' -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I../inst/include -fopenmp -fPIC -pipe -Os -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64 -c RcppExports.cpp -o RcppExports.o
    In file included from RcppExports.cpp:4:
    In file included from ./../inst/include/RcppEnsmallen.h:25:
    In file included from ../inst/include/ensmallen.hpp:75:
    ../inst/include/ensmallen_bits/callbacks/callbacks.hpp:765:26: error: no member named 'HasGenerationalStepTakenSignature' in namespace 'ens::callbacks::traits'
    callbacks::traits::HasGenerationalStepTakenSignature<
    ~~~~~~~~~~~~~~~~~~~^
    ../inst/include/ensmallen_bits/callbacks/callbacks.hpp:766:7: error: 'CallbackType' does not refer to a value
    CallbackType, OptimizerType, FunctionType, MatType, ObjectivesVecType,
    ^
    ../inst/include/ensmallen_bits/callbacks/callbacks.hpp:758:21: note: declared here
    template<typename CallbackType,
    ^
    ../inst/include/ensmallen_bits/callbacks/callbacks.hpp:767:28: error: expected member name or ';' after declaration specifiers
    IndicesType>::hasBool, bool>::type
    ~~~~~~~~~~~~~~~~~~~~~^

**Comment by coatless** [comment]
From CRAN: 

https://cran.r-project.org/web/checks/check_results_RcppEnsmallen.html

There isn't an issue being detected.

Thus, I think this is a local problem due to the installation being custom. From the log, I can't see an immediate issue. 

Please use the official CRAN binaries
