### ISSUE TITLE
Ensmallen 2.20 released

### ISSUE THREAD

**Issue by eddelbuettel** [coatless-rpkg/rcppensmallen#56]
See https://sourceforge.net/p/arma/news/2023/10/ensmallen-220-released---c-library-for-numerical-optimisation/

It looks like you just gave the automated procedure some love last night but it also looks like it didn't catch this.

**Comment by coatless** [comment]
Unfortunately, the GH page was "stuck" without a tag/release designation. As of ~53 minutes ago, we now have a tag for the runner to use. 

https://github.com/mlpack/ensmallen/releases/tag/2.20.0

The only other downside is the GH Runner is set to only run once a day at 10:00:00. 

https://github.com/coatless-rpkg/rcppensmallen/blob/43013c9410219d788df20af1b0f7b74000f0bc56/.github/workflows/upstream-refresh.yaml#L5

But, the positive side is there's a manual trigger on the action that I just triggered. Now, we have everything updated at #57! 🎉

**Comment by eddelbuettel** [comment]
Nice.

> The only other downside is the GH Runner is set to only run once a day at 10:00:00.

You may know this already but there is a different trigger you can add namely [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) which then also gives you a manual toggle on the Action webpage.  But hey daily is good too.

**Comment by eddelbuettel** [comment]
>  there's a manual trigger on the action that I just triggered

Doh. I missed that.  So we mentioned the same thing to each other.
